#!/bin/bash

source /etc/tls-refresh/.env
certpath="/etc/haproxy/certs/$domain.pem"
haproxycert="/usr/local/etc/haproxy/certs/$domain.pem"

cat \
  /etc/letsencrypt/live/"$domain"/fullchain.pem \
  /etc/letsencrypt/live/"$domain"/privkey.pem \
  > "$certpath"

certdata="$(cat certpath)"

echo "Updating HAProxy..."

echo -e "set ssl cert $haproxycert <<\n$certdata\n" | socat tcp-connect:gateway:9999 -
echo "show ssl cert *$haproxycert" | socat tcp-connect:gateway:9999 -
echo "commit ssl cert $haproxycert" | socat tcp-connect:gateway:9999 -
echo "show ssl cert $haproxycert" | socat tcp-connect:gateway:9999 -

echo "Updated HAProxy"
